### PR TITLE
Replace Cake PHP framework with Loopback.js server

### PR DESCRIPTION
**Pull request by wdoug**
This decision is based mainly around the expertise of the people working on the project.

### CODE REVIEW

**Comment by jdepree** [comment]
We should be careful to keep mobile in mind.
screenshot_2015-08-04-09-35-45
screenshot_2015-08-04-09-35-16

**Comment by wdoug** [comment]
@jdepree agreed!

**Comment by wdoug** [comment]
I am going to merge this for the time being, and then we can decide what we should do for mobile.

**Comment by raemacias** [comment]
Should I just do some media query code in the css to help the mobile part?

**Pull request merged**
